version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo-network

  backend:
    image: mericalp/mern-todo-backend:v1
    ports:
      - "5100:5001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mern-todo
    depends_on:
      - mongodb
    networks:
      - todo-network
    deploy:
      replicas: 2

  frontend:
    image: mericalp/mern-todo-frontend:v1
    ports:
      - "3100:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5100
    depends_on:
      - backend
    networks:
      - todo-network
    deploy:
      replicas: 2

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - todo-network

networks:
  todo-network:
    external: true

volumes:
  mongodb_data: